- environment.yml
- notebooks/consumer.qmd
- notebooks/index.qmd
- src/data/data_process.py
- src/data/data_pull.py
- Added function to download files from [this](https://jp.pr.gov/wp-content/uploads/2024/09/Indicadores_Economicos_9.13.2024.xlsx)
- Added function to extract the data from the sheet  `process_sheet()`
- Added function to transform the data into panel format `process_panel()`
- Added function to combine all the data from the sheets into a single data frame `process_jp_index()`
> [!WARNING]  
> The `process_sheet()` function my be prone to change given any change in format from the data source.
> Added function to get the JP index

- .gitignore
- environment.yml
- main.py
- notebooks/consumer.qmd
- notebooks/db.qmd
- src/dao/consumer_table.py
- src/dao/economic_indicators_table.py
- src/data/data_process.py
- src/data/data_pull.py
- Added support for database url from SQLalchamy
- added docstring to some of the functions
- clean the code
> Added DB support 

- environment.yml
- src/dao/awards_table.py
- src/data/awards_process.py
- src/data/awards_pull.py
- src/data/pull_awards.py
Currently, the script downloads and saves awards filtered by Puerto Rico and the year 2008. In the future, the goal is to expand this functionality to cover all years and integrate the data into the database.
> Downloading-awards

- notebooks/graph.qmd
- pyproject.toml
- src/data/data_process.py
- src/graphs.py
#21 created graphs for categories and agency
> awards graphs

- pyproject.toml
- src/graphs.py
> 41 graph dimensions

- pyproject.toml
- src/graphs.py
This fix some issues of the energy graph 
issue: #47
> Arreglos a la grafica para mantener coherencia con el resto de graficas.

- src/data/data_pull.py
- src/graphs.py
fixed awards graph functions and edited data
> 46 fix awards

- pyproject.toml
- src/data/data_pull.py
added function to retry awards download if file not ready
> 52 incomplete download

- pyproject.toml
- src/data/data_pull.py
- src/graphs.py
Update the function pull_energy_data and the function create_energy_graph to make a full connected version that can be use by the same endpoint at the moment of show the graph on webapp
issue: #49
> #49 merge functionalities for energy data

- pyproject.toml
- src/data/data_pull.py
- src/graphs.py
added error handling and graph width fix
> error handling and width fix

- pyproject.toml
- src/graphs.py
changed data range for indicadores graphs and tick marks
> 59 range data

- pyproject.toml
- src/data/data_pull.py
- src/graphs.py
Se implementó la función de process_energy_data con al cual se genera la gráfica y próximamente la data que se descarga.
issue: #54
> creacion de process energy data

- pyproject.toml
- src/data/data_pull.py
se modifica la consulta del select para que se vea en orden
> 80 fix energy data

- pyproject.toml
- src/data/data_process.py
- src/data/data_pull.py
- src/graphs.py
added column mapping for indicators and mapping for when to use mean or sum
> 85 indicadores mapping

- pyproject.toml
- src/data/data_process.py
- src/graphs.py
created new graphs for demographic data
> 88 demografico

- pyproject.toml
- src/graphs.py
sorted returned columns for jp cycle graph
> sorted columns

- pyproject.toml
- src/data/data_pull.py
hotfix en los procesos de descarga de la data de energy y gatos estatales
> hotfix en energy data and gastos estatales processes

- pyproject.toml
- src/graphs.py
aregle un error con fiscal, yearly y quaterly.
> Hotfix speding data

- src/data/data_pull.py
limites dropdown options in awards category to options in USA spending graph
> limited awards category columns

- src/data/data_process.py
changed from sum to mean (promedio)
> change sum of values to mean

- pyproject.toml
- src/graphs.py
se arreglaron algunos valores de los dropdown en energy y estatales
> hotfix actualizaciones a estatales
